### ISSUE TITLE
Seperate style (CSS?) for printing

### ISSUE THREAD

**Issue by natrius** [zorgluf/souvenirs-android#12]
While i have dark mode on my smartphone i might want to print, uh, 'regular' for others to view it, for example.

**Comment by zorgluf** [comment]
Hi Natrius,
Sorry, I don't get your point : do you try to print an album from the android application ? Or do you want to send an album to others non-souvenirs users ? (you can export them to PDF form the app).

**Comment by natrius** [comment]
Export to PDF from android PDF is usally referred to as "Print to PDF". Just thought its the same as on HTML (therefore CSS)
