### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [zorgluf/souvenirs-android#13]
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':app:releaseCompileClasspath'.
   > Could not find com.github.nextcloud:Android-SingleSignOn:0.5.1.
     Required by:
         project :app
```

Could you please take a look? It seems like a network issue but it fails several times. Thanks!

**Comment by linsui** [comment]
Ah, nevermind, the new version builds fine.

**Comment by zorgluf** [comment]
No harms done, thanks for reporting.
It seemed that this library from nextcloud disappeared, I updated it to the latest version on the new build.
