### ISSUE TITLE
NonFree lib in F-Droid build

### ISSUE THREAD

**Issue by linsui** [zorgluf/souvenirs-android#16]
https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1011 androidx.core:core-google-shortcuts depends on firebase. Could you please take a look? Thanks!

**Comment by zorgluf** [comment]
Thanks for the report. This dep was introduced in shared shortcut functionalities but seams not necessary. A mistake from my side, sorry. It will be removed on next release expected in August. Is it too late? If yes, I will issue a quick fix release.

**Comment by linsui** [comment]
I have disabled affected versions. No need to be hurry. If it's a easy fix, e.g just removing the dep, I can do that on our side.

**Comment by zorgluf** [comment]
No need, I had a few time to push the commits in release 2.6.1. Done.
