### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by lgwapnitsky** [zorgluf/souvenirs-android#17]
Added nextcloud sync, now crashes whenever app starts. Running android.12

**Comment by zorgluf** [comment]
Thanks for the report.
I will need a little more information to reproduce : 
* Did you manage to select a nextcloud account when enabling sync ?
* Did you installed the souvenirs app on your nextcloud server ?
* Which version of android application are you using ? Same question for the nextcloud souvenirs app.
If you can have a logcat extraction when the application crash, it would greatly help.
Thanks in advance,

**Comment by lgwapnitsky** [comment]
See responses below.  Also, able to sync, but now crashes when trying to
change the layout
