### ISSUE TITLE
App don't Open

### ISSUE THREAD

**Issue by weinic** [zorgluf/souvenirs-android#3]
Hello, 
the App don't open on my OnePlus5.
This crashes on each opening.

**Comment by zorgluf** [comment]
Hi,
Thanks for your report.
Could you give me the version you are using ? 2.0.0 has known issues on app opening on some android devices.
Could you provide also some logcat output ?
Thanks,

**Comment by weinic** [comment]
I used the Version 2.0.1 from F-Droid Store.
I'm trying to get a logcat output.

**Comment by weinic** [comment]
here is my logcat output
[souvenirs-fail.txt](https://github.com/zorgluf/souvenirs-android/files/6189364/souvenirs-fail.txt)

**Comment by zorgluf** [comment]
Thanks !
The commit 1606af54be58167b8d6112fe8ff24fee0d4f89b1 should fixed the issue.
I will release a new version. Should be avalaible within a week on f-droid.
