### ISSUE TITLE
F-Droid build failed: please update gradle

### ISSUE THREAD

**Issue by linsui** [zorgluf/souvenirs-android#7]
Please also update https://github.com/zorgluf/souvenirs-android/blob/v2.2.0/app/gradle/wrapper/gradle-wrapper.properties to 7.0.2 or remove it. Thanks!

**Comment by zorgluf** [comment]
Thanks for report, fixed in v2.2.1 (4240c3f25ed1eed6e04e0b5adf5738b34b89d659)
