### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by petrisch** [zorgluf/souvenirs-android#8]
So since this is the first issue, I think I'm aloud to be not so precise ;-)
I managed to install both apps on Android and on my nextcloud.

I was able to make a Album on the Android App, which is the only way I suppose?
However it generated only the title. Then got synced with nextcloud.
With pictures, taken from my phone it doesn't sync to the cloud.

Whats maybe to consider doing right or bad?
The sync on the phone notificates, but turns forever...

**Comment by zorgluf** [comment]
Yes, the album can only generated on Android app for the moment.
Sometimes sync stalled without timeout, I will investigate. Just close the app and retry. 
If it's still not working, do you have any possibilities to send a logcat ?
